# Generated by Django 5.0.3 on 2024-04-02 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('izzy_tech_consulting', '0003_user_is_consultant_user_is_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='service',
            name='duration_minutes',
        ),
    ]
