# Generated by Django 5.0.3 on 2024-04-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izzy_tech_consulting', '0004_remove_service_duration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
