# Generated by Django 5.0.3 on 2024-04-01 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('izzy_tech_consulting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_consultant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
    ]
