# Generated by Django 5.0.3 on 2024-04-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izzy_tech_consulting', '0002_remove_user_is_consultant_remove_user_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_consultant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
